BEGIN;

DROP TABLE IF EXISTS event_receipts;
DROP TABLE IF EXISTS outbox_events;
DROP TRIGGER IF EXISTS audit_entries_immutable ON audit_entries;
DROP FUNCTION IF EXISTS reject_audit_mutation();
DROP TABLE IF EXISTS audit_entries;
DROP TABLE IF EXISTS wager_settlements;
DROP TABLE IF EXISTS market_settlement_outcomes;
DROP TABLE IF EXISTS market_settlements;
DROP TABLE IF EXISTS wagers;
DROP TABLE IF EXISTS market_restrictions;
DROP TABLE IF EXISTS selections;
DROP TABLE IF EXISTS markets;
DROP TRIGGER IF EXISTS ledger_posting_preserves_balance ON ledger_postings;
DROP TRIGGER IF EXISTS ledger_transaction_requires_balanced_postings ON ledger_transactions;
DROP FUNCTION IF EXISTS check_ledger_transaction_balanced();
DROP TRIGGER IF EXISTS ledger_postings_immutable ON ledger_postings;
DROP TRIGGER IF EXISTS ledger_transactions_immutable ON ledger_transactions;
DROP FUNCTION IF EXISTS reject_ledger_mutation();
DROP TABLE IF EXISTS ledger_postings;
DROP TABLE IF EXISTS ledger_transactions;
DROP TABLE IF EXISTS ledger_accounts;
DROP TABLE IF EXISTS media_player_links;
DROP TABLE IF EXISTS media_match_links;
DROP TABLE IF EXISTS media_event_links;
DROP TABLE IF EXISTS media_assets;
DROP TABLE IF EXISTS player_stat_projections;
DROP TABLE IF EXISTS legacy_stat_snapshots;
DROP TABLE IF EXISTS legacy_import_records;
DROP TABLE IF EXISTS migration_batches;
DROP TABLE IF EXISTS verified_results;
DROP TABLE IF EXISTS result_confirmations;
DROP TABLE IF EXISTS result_submissions;
DROP TABLE IF EXISTS match_participants;
DROP TABLE IF EXISTS match_sides;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS event_team_memberships;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS player_aliases;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS invitations;
DROP TABLE IF EXISTS memberships;
DROP TABLE IF EXISTS auth_identities;
DROP TABLE IF EXISTS users;

COMMIT;
