package bettingpg

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/dgunzy/go-book/internal/betting"
	"github.com/dgunzy/go-book/internal/ledger"
	"github.com/jackc/pgx/v5"
)

// ErrAlreadyReversed is returned when a settle-up has already been backed out.
// The correcting entry is posted once; a second one would move the balance a
// second time.
var ErrAlreadyReversed = errors.New("bettingpg: this settlement was already reversed")

// RecordSettlementRequest records money that changed hands outside the app.
// AdjustmentID is generated by the caller so a resubmitted form collides on the
// ledger's idempotency key instead of posting twice.
type RecordSettlementRequest struct {
	AdjustmentID string
	UserID       string
	ActorUserID  string
	Direction    betting.AdjustmentDirection
	AmountCents  int64
	Currency     ledger.Currency
	Reason       string
}

// SettlementRow is one recorded settle-up for the admin history.
type SettlementRow struct {
	AdjustmentID  string
	TransactionID string
	UserID        string
	MemberName    string
	Direction     betting.AdjustmentDirection
	Amount        ledger.Money
	Reason        string
	ActorName     string
	OccurredAt    time.Time
	// Reversed is set when a correcting entry has cancelled this row. The
	// original always stays visible: ledger history is never deleted.
	Reversed       bool
	ReversedReason string
	ReversedAt     time.Time
}

// MemberBalanceRow is what one member owes the book, or is owed by it. It is
// their cash position — betting results less anything already settled up — and
// is deliberately separate from their profit and loss.
type MemberBalanceRow struct {
	UserID  string
	Name    string
	Balance ledger.Money
}

// Owed reports whether the book owes this member money.
func (r MemberBalanceRow) Owed() bool { return r.Balance.Cents > 0 }

// Owes reports whether this member owes the book money.
func (r MemberBalanceRow) Owes() bool { return r.Balance.Cents < 0 }

// RecordSettlement posts a member's payment or payout to the ledger. No wager
// is graded and escrow is untouched: this only records that real-world money
// moved, so the member's balance reflects what is still outstanding. Posting is
// idempotent on the adjustment ID.
func (s Store) RecordSettlement(ctx context.Context, request RecordSettlementRequest) (SettlementRow, error) {
	if !isUUID(request.AdjustmentID) || !isUUID(request.UserID) {
		return SettlementRow{}, fmt.Errorf("%w: a settlement needs an adjustment and member ID", betting.ErrInvalid)
	}
	if !isUUID(request.ActorUserID) {
		return SettlementRow{}, betting.ErrUnauthorized
	}
	tx, err := s.begin(ctx)
	if err != nil {
		return SettlementRow{}, err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// A resubmitted form must not post a second time. The unique
	// (currency, idempotency_key) index is the real guard; this read turns the
	// duplicate into a quiet no-op rather than a constraint error.
	existing, found, err := loadSettlement(ctx, tx, request.AdjustmentID)
	if err != nil {
		return SettlementRow{}, err
	}
	if found {
		if err := tx.Commit(ctx); err != nil {
			return SettlementRow{}, fmt.Errorf("commit settlement (idempotent): %w", err)
		}
		return existing, nil
	}

	if err := requireMember(ctx, tx, request.UserID); err != nil {
		return SettlementRow{}, err
	}
	userAccountID, err := ensureUserAccount(ctx, tx, request.UserID, betting.FundingUserCash, request.Currency)
	if err != nil {
		return SettlementRow{}, err
	}
	houseAccountID, err := ensureSystemAccount(ctx, tx, "house_clearing", request.Currency)
	if err != nil {
		return SettlementRow{}, err
	}

	transaction, err := betting.RecordAdjustment(betting.AdjustmentCommand{
		AdjustmentID: request.AdjustmentID,
		UserID:       betting.ID(request.UserID),
		Direction:    request.Direction,
		Amount:       ledger.Money{Cents: request.AmountCents, Currency: request.Currency},
		Reason:       request.Reason,
		Actor:        betting.ID(request.ActorUserID),
		Refs: betting.AdjustmentAccountRefs{
			UserFundingAccountID: userAccountID, HouseClearingAccountID: houseAccountID,
		},
		OccurredAt: time.Now(),
	})
	if err != nil {
		return SettlementRow{}, err
	}
	if _, err := insertLedgerTransaction(ctx, tx, transaction); err != nil {
		return SettlementRow{}, err
	}

	row, _, err := loadSettlement(ctx, tx, request.AdjustmentID)
	if err != nil {
		return SettlementRow{}, err
	}
	if err := tx.Commit(ctx); err != nil {
		return SettlementRow{}, fmt.Errorf("commit settlement: %w", err)
	}
	return row, nil
}

// ReverseSettlement backs out a settle-up that should not have been recorded by
// posting the exact inverse against the same two accounts. Nothing is edited or
// deleted: the original and its reversal both stay in the ledger, and the
// member's balance returns to where it was.
func (s Store) ReverseSettlement(ctx context.Context, adjustmentID, actorUserID, reason string) (SettlementRow, error) {
	if !isUUID(adjustmentID) {
		return SettlementRow{}, fmt.Errorf("%w: settlement %s", betting.ErrNotFound, adjustmentID)
	}
	if !isUUID(actorUserID) {
		return SettlementRow{}, betting.ErrUnauthorized
	}
	tx, err := s.begin(ctx)
	if err != nil {
		return SettlementRow{}, err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	original, transactionID, err := loadAdjustmentTransaction(ctx, tx, adjustmentID)
	if err != nil {
		return SettlementRow{}, err
	}
	reversed, err := settlementIsReversed(ctx, tx, transactionID)
	if err != nil {
		return SettlementRow{}, err
	}
	if reversed {
		return SettlementRow{}, ErrAlreadyReversed
	}

	reversal, err := betting.ReverseAdjustment(original, transactionID, betting.ID(actorUserID), reason)
	if err != nil {
		return SettlementRow{}, err
	}
	if _, err := insertLedgerTransaction(ctx, tx, reversal); err != nil {
		return SettlementRow{}, err
	}

	row, _, err := loadSettlement(ctx, tx, adjustmentID)
	if err != nil {
		return SettlementRow{}, err
	}
	if err := tx.Commit(ctx); err != nil {
		return SettlementRow{}, fmt.Errorf("commit settlement reversal: %w", err)
	}
	return row, nil
}

func requireMember(ctx context.Context, tx pgx.Tx, userID string) error {
	var exists bool
	if err := tx.QueryRow(ctx, `SELECT true FROM users WHERE id = $1::uuid`, userID).Scan(&exists); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return fmt.Errorf("%w: user %s", betting.ErrNotFound, userID)
		}
		return fmt.Errorf("load settlement member: %w", err)
	}
	return nil
}

// loadAdjustmentTransaction rebuilds the original settle-up transaction and its
// postings so the reversal can be its exact inverse.
func loadAdjustmentTransaction(ctx context.Context, tx pgx.Tx, adjustmentID string) (ledger.Transaction, string, error) {
	var transactionID, currency, reason, sourceID string
	err := tx.QueryRow(ctx, `
		SELECT id::text, currency::text, coalesce(reason, ''), source_id::text
		FROM ledger_transactions
		WHERE transaction_type = 'admin_adjustment' AND source_type = $1 AND source_id = $2::uuid`,
		betting.AdjustmentSourceType, adjustmentID).Scan(&transactionID, &currency, &reason, &sourceID)
	if errors.Is(err, pgx.ErrNoRows) {
		return ledger.Transaction{}, "", fmt.Errorf("%w: settlement %s", betting.ErrNotFound, adjustmentID)
	}
	if err != nil {
		return ledger.Transaction{}, "", fmt.Errorf("load settlement transaction: %w", err)
	}
	parsedCurrency, err := ledger.ParseCurrency(currency)
	if err != nil {
		return ledger.Transaction{}, "", fmt.Errorf("settlement %s currency: %w", adjustmentID, err)
	}

	rows, err := tx.Query(ctx, `
		SELECT account_id::text, amount_cents FROM ledger_postings WHERE transaction_id = $1::uuid ORDER BY id`,
		transactionID)
	if err != nil {
		return ledger.Transaction{}, "", fmt.Errorf("load settlement postings: %w", err)
	}
	defer rows.Close()
	original := ledger.Transaction{
		Type: ledger.TransactionAdminAdjustment, Currency: parsedCurrency,
		SourceType: betting.AdjustmentSourceType, SourceID: sourceID, Reason: reason,
	}
	for rows.Next() {
		var accountID string
		var amount int64
		if err := rows.Scan(&accountID, &amount); err != nil {
			return ledger.Transaction{}, "", fmt.Errorf("scan settlement posting: %w", err)
		}
		original.Postings = append(original.Postings, ledger.Posting{
			AccountID: accountID, Amount: ledger.Money{Cents: amount, Currency: parsedCurrency},
		})
	}
	if err := rows.Err(); err != nil {
		return ledger.Transaction{}, "", fmt.Errorf("iterate settlement postings: %w", err)
	}
	return original, transactionID, nil
}

func settlementIsReversed(ctx context.Context, tx pgx.Tx, transactionID string) (bool, error) {
	var reversed bool
	err := tx.QueryRow(ctx,
		`SELECT exists(SELECT 1 FROM ledger_transactions WHERE reversal_of_transaction_id = $1::uuid)`,
		transactionID).Scan(&reversed)
	if err != nil {
		return false, fmt.Errorf("check settlement reversal: %w", err)
	}
	return reversed, nil
}

// settlementRowsSQL reads recorded settle-ups with the member and admin behind
// each one, and whether a correcting entry has since cancelled it.
const settlementRowsSQL = `
SELECT t.source_id::text, t.id::text, member.id::text, member.display_name,
       CASE WHEN p.amount_cents > 0 THEN 'payment_received' ELSE 'payout_sent' END,
       abs(p.amount_cents), t.currency::text, coalesce(t.reason, ''),
       coalesce(actor.display_name, 'system'), t.occurred_at,
       reversal.id IS NOT NULL, coalesce(reversal.reason, ''), reversal.occurred_at
FROM ledger_transactions t
JOIN ledger_postings p ON p.transaction_id = t.id
JOIN ledger_accounts a ON a.id = p.account_id AND a.owner_user_id IS NOT NULL
JOIN users member ON member.id = a.owner_user_id
LEFT JOIN users actor ON actor.id = t.actor_user_id
LEFT JOIN ledger_transactions reversal ON reversal.reversal_of_transaction_id = t.id
WHERE t.transaction_type = 'admin_adjustment' AND t.source_type = '` + betting.AdjustmentSourceType + `'
%s
ORDER BY t.occurred_at DESC, t.id DESC
%s`

// ListSettlements returns the most recent settle-ups across the book.
func (s Store) ListSettlements(ctx context.Context, limit int) ([]SettlementRow, error) {
	if s.DB == nil {
		return nil, errors.New("bettingpg: PostgreSQL pool is required")
	}
	if limit <= 0 {
		limit = 50
	}
	rows, err := s.DB.Query(ctx, fmt.Sprintf(settlementRowsSQL, "", "LIMIT $1"), limit)
	if err != nil {
		return nil, fmt.Errorf("query settlements: %w", err)
	}
	defer rows.Close()
	return scanSettlements(rows)
}

// loadSettlement reads one settle-up inside an open transaction.
func loadSettlement(ctx context.Context, tx pgx.Tx, adjustmentID string) (SettlementRow, bool, error) {
	rows, err := tx.Query(ctx, fmt.Sprintf(settlementRowsSQL, "AND t.source_id = $1::uuid", ""), adjustmentID)
	if err != nil {
		return SettlementRow{}, false, fmt.Errorf("query settlement: %w", err)
	}
	defer rows.Close()
	found, err := scanSettlements(rows)
	if err != nil {
		return SettlementRow{}, false, err
	}
	if len(found) == 0 {
		return SettlementRow{}, false, nil
	}
	return found[0], true, nil
}

func scanSettlements(rows pgx.Rows) ([]SettlementRow, error) {
	result := make([]SettlementRow, 0)
	for rows.Next() {
		var row SettlementRow
		var direction, currency string
		var amount int64
		var reversedAt *time.Time
		if err := rows.Scan(&row.AdjustmentID, &row.TransactionID, &row.UserID, &row.MemberName,
			&direction, &amount, &currency, &row.Reason, &row.ActorName, &row.OccurredAt,
			&row.Reversed, &row.ReversedReason, &reversedAt); err != nil {
			return nil, fmt.Errorf("scan settlement: %w", err)
		}
		parsedCurrency, err := ledger.ParseCurrency(currency)
		if err != nil {
			return nil, fmt.Errorf("settlement %s currency: %w", row.AdjustmentID, err)
		}
		row.Direction = betting.AdjustmentDirection(direction)
		row.Amount = ledger.Money{Cents: amount, Currency: parsedCurrency}
		row.OccurredAt = row.OccurredAt.UTC()
		if reversedAt != nil {
			row.ReversedAt = reversedAt.UTC()
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate settlements: %w", err)
	}
	return result, nil
}

// ListMemberBalances returns every member's cash position: negative means they
// owe the book, positive means the book owes them. Members who are square are
// left out.
func (s Store) ListMemberBalances(ctx context.Context, currency ledger.Currency) ([]MemberBalanceRow, error) {
	if s.DB == nil {
		return nil, errors.New("bettingpg: PostgreSQL pool is required")
	}
	rows, err := s.DB.Query(ctx, memberBalancesSQL, string(currency))
	if err != nil {
		return nil, fmt.Errorf("query member balances: %w", err)
	}
	defer rows.Close()

	result := make([]MemberBalanceRow, 0)
	for rows.Next() {
		var row MemberBalanceRow
		var cents int64
		if err := rows.Scan(&row.UserID, &row.Name, &cents); err != nil {
			return nil, fmt.Errorf("scan member balance: %w", err)
		}
		row.Balance = ledger.Money{Cents: cents, Currency: currency}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate member balances: %w", err)
	}
	return result, nil
}

const memberBalancesSQL = `
SELECT u.id::text, u.display_name, coalesce(b.balance_cents, 0)::bigint
FROM users u
JOIN ledger_account_balances b ON b.owner_user_id = u.id
    AND b.account_type = 'user_cash' AND b.currency::text = $1
WHERE b.balance_cents <> 0
ORDER BY b.balance_cents, u.display_name`
